from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
        self.tab = None
        self.line = None
        self.tab_3 = None
        self.tab_2 = None
        self.label = None
        self.line_2 = None
        self.lineDb = None
        self.line_4 = None
        self.line_5 = None
        self.line_6 = None
        self.line_3 = None
        self.lineFW4 = None
        self.lineRV4 = None
        self.lineSD4 = None
        self.lineSD3 = None
        self.lineFW3 = None
        self.lineRV3 = None
        self.label_4 = None
        self.label_8 = None
        self.label_7 = None
        self.label_3 = None
        self.label_6 = None
        self.label_5 = None
        self.label_9 = None
        self.lineRV2 = None
        self.lineSD2 = None
        self.lineFW2 = None
        self.label_2 = None
        self.menubar = None
        self.menuFile = None
        self.lineEdit = None
        self.lineFile = None
        self.lineGen2 = None
        self.lineGen3 = None
        self.linePos3 = None
        self.label_16 = None
        self.label_17 = None
        self.lineFin3 = None
        self.label_19 = None
        self.label_18 = None
        self.label_20 = None
        self.lineGen4 = None
        self.comboBox = None
        self.label_25 = None
        self.lineTask = None
        self.lineFin4 = None
        self.label_21 = None
        self.linePos4 = None
        self.label_22 = None
        self.label_23 = None
        self.label_24 = None
        self.label_14 = None
        self.linePos2 = None
        self.linePos1 = None
        self.label_13 = None
        self.label_12 = None
        self.label_11 = None
        self.label_15 = None
        self.label_10 = None
        self.lineGen1 = None
        self.lineFin2 = None
        self.lineFin1 = None
        self.statusbar = None
        self.geneCombo = None
        self.lineProd3 = None
        self.labelTask = None
        self.lineProd4 = None
        self.lineEmail = None
        self.lineProd2 = None
        self.lineProd1 = None
        self.tabWidget = None
        self.lineMScore = None
        self.lineEdit_3 = None
        self.lineEdit_2 = None
        self.labelSonda = None
        self.lineFile_2 = None
        self.pushButton = None
        self.gridLayout = None
        self.geneCombo_2 = None
        self.lineInicio3 = None
        self.labelTask_2 = None
        self.labelTask_3 = None
        self.lineMaxSeqs = None
        self.comboDianas = None
        self.geneCombo_4 = None
        self.geneCombo_3 = None
        self.lineInicio2 = None
        self.lineInicio1 = None
        self.lineInicio4 = None
        self.lineEGScore = None
        self.lineOGScore = None
        self.lineMMScore = None
        self.labelSonda_2 = None
        self.labelSonda_3 = None
        self.labelForward = None
        self.lineEditBlSD = None
        self.labelSonda_6 = None
        self.labelSonda_9 = None
        self.lineEditBlFW = None
        self.lineEditBlRV = None
        self.labelMaxSeqs = None
        self.pushButton_3 = None
        self.labelSonda_8 = None
        self.labelSonda_7 = None
        self.gridLayout_2 = None
        self.labelSonda_5 = None
        self.pushButton_2 = None
        self.labelSonda_4 = None
        self.labelReverse = None
        self.lineMaxSeqs_2 = None
        self.lineNombreOut = None
        self.labelSonda_11 = None
        self.labelSonda_10 = None
        self.centralwidget = None
        self.labelForward_6 = None
        self.labelForward_5 = None
        self.labelMaxSeqs_2 = None
        self.checkBoxRemote = None
        self.labelForward_8 = None
        self.labelForward_7 = None
        self.labelReverse_4 = None
        self.labelReverse_3 = None
        self.labelReverse_2 = None
        self.labelForward_4 = None
        self.labelForward_3 = None
        self.labelForward_2 = None
        self.labelForward_9 = None
        self.labelReverse_5 = None
        self.pushButtonFile = None
        self.pushButtonFile_2 = None
        self.pushButtonFile_3 = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 1009)
        MainWindow.setMinimumSize(QtCore.QSize(850, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.labelSonda_4 = QtWidgets.QLabel(self.tab)
        self.labelSonda_4.setGeometry(QtCore.QRect(20, 760, 138, 16))
        self.labelSonda_4.setObjectName("labelSonda_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(321, 867, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(411, 867, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(10, 0, 811, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineMMScore = QtWidgets.QLineEdit(self.tab)
        self.lineMMScore.setGeometry(QtCore.QRect(161, 825, 41, 20))
        self.lineMMScore.setObjectName("lineMMScore")
        self.labelReverse = QtWidgets.QLabel(self.tab)
        self.labelReverse.setGeometry(QtCore.QRect(10, 274, 112, 16))
        self.labelReverse.setObjectName("labelReverse")
        self.lineMScore = QtWidgets.QLineEdit(self.tab)
        self.lineMScore.setGeometry(QtCore.QRect(161, 795, 41, 20))
        self.lineMScore.setObjectName("lineMScore")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 877, 121, 16))
        self.label_4.setObjectName("label_4")
        self.lineOGScore = QtWidgets.QLineEdit(self.tab)
        self.lineOGScore.setGeometry(QtCore.QRect(161, 851, 41, 20))
        self.lineOGScore.setObjectName("lineOGScore")
        self.labelSonda = QtWidgets.QLabel(self.tab)
        self.labelSonda.setGeometry(QtCore.QRect(10, 300, 90, 16))
        self.labelSonda.setObjectName("labelSonda")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 825, 121, 16))
        self.label_2.setObjectName("label_2")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(10, 740, 821, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 799, 121, 16))
        self.label.setObjectName("label")
        self.lineEGScore = QtWidgets.QLineEdit(self.tab)
        self.lineEGScore.setGeometry(QtCore.QRect(161, 877, 41, 20))
        self.lineEGScore.setObjectName("lineEGScore")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 851, 121, 16))
        self.label_3.setObjectName("label_3")
        self.labelForward = QtWidgets.QLabel(self.tab)
        self.labelForward.setGeometry(QtCore.QRect(10, 248, 112, 16))
        self.labelForward.setObjectName("labelForward")
        self.labelSonda_3 = QtWidgets.QLabel(self.tab)
        self.labelSonda_3.setGeometry(QtCore.QRect(9, 218, 189, 16))
        self.labelSonda_3.setObjectName("labelSonda_3")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(140, 248, 261, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 274, 261, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 300, 261, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.labelSonda_2 = QtWidgets.QLabel(self.tab)
        self.labelSonda_2.setGeometry(QtCore.QRect(9, 18, 391, 16))
        self.labelSonda_2.setObjectName("labelSonda_2")
        self.lineFile = QtWidgets.QLineEdit(self.tab)
        self.lineFile.setGeometry(QtCore.QRect(10, 40, 821, 20))
        self.lineFile.setObjectName("lineFile")
        self.pushButtonFile = QtWidgets.QPushButton(self.tab)
        self.pushButtonFile.setGeometry(QtCore.QRect(720, 90, 101, 23))
        self.pushButtonFile.setObjectName("pushButtonFile")
        self.geneCombo = QtWidgets.QComboBox(self.tab)
        self.geneCombo.setGeometry(QtCore.QRect(9, 180, 75, 20))
        self.geneCombo.setObjectName("geneCombo")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo.addItem("")
        self.geneCombo_2 = QtWidgets.QComboBox(self.tab)
        self.geneCombo_2.setEnabled(False)
        self.geneCombo_2.setGeometry(QtCore.QRect(430, 190, 75, 20))
        self.geneCombo_2.setObjectName("geneCombo_2")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.geneCombo_2.addItem("")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(0, 130, 821, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.labelForward_2 = QtWidgets.QLabel(self.tab)
        self.labelForward_2.setGeometry(QtCore.QRect(10, 150, 71, 16))
        self.labelForward_2.setObjectName("labelForward_2")
        self.labelForward_3 = QtWidgets.QLabel(self.tab)
        self.labelForward_3.setGeometry(QtCore.QRect(430, 150, 71, 16))
        self.labelForward_3.setObjectName("labelForward_3")
        self.labelSonda_6 = QtWidgets.QLabel(self.tab)
        self.labelSonda_6.setGeometry(QtCore.QRect(430, 296, 90, 16))
        self.labelSonda_6.setObjectName("labelSonda_6")
        self.lineFW2 = QtWidgets.QLineEdit(self.tab)
        self.lineFW2.setEnabled(False)
        self.lineFW2.setGeometry(QtCore.QRect(560, 244, 261, 20))
        self.lineFW2.setObjectName("lineFW2")
        self.lineSD2 = QtWidgets.QLineEdit(self.tab)
        self.lineSD2.setEnabled(False)
        self.lineSD2.setGeometry(QtCore.QRect(560, 296, 261, 20))
        self.lineSD2.setObjectName("lineSD2")
        self.lineRV2 = QtWidgets.QLineEdit(self.tab)
        self.lineRV2.setEnabled(False)
        self.lineRV2.setGeometry(QtCore.QRect(560, 270, 261, 20))
        self.lineRV2.setObjectName("lineRV2")
        self.labelForward_4 = QtWidgets.QLabel(self.tab)
        self.labelForward_4.setGeometry(QtCore.QRect(430, 244, 112, 16))
        self.labelForward_4.setObjectName("labelForward_4")
        self.labelReverse_2 = QtWidgets.QLabel(self.tab)
        self.labelReverse_2.setGeometry(QtCore.QRect(430, 270, 112, 16))
        self.labelReverse_2.setObjectName("labelReverse_2")
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setGeometry(QtCore.QRect(403, 140, 20, 601))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 330, 41, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(210, 330, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 360, 41, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(220, 360, 41, 16))
        self.label_8.setObjectName("label_8")
        self.lineGen1 = QtWidgets.QLineEdit(self.tab)
        self.lineGen1.setEnabled(False)
        self.lineGen1.setGeometry(QtCore.QRect(90, 330, 113, 20))
        self.lineGen1.setObjectName("lineGen1")
        self.lineProd1 = QtWidgets.QLineEdit(self.tab)
        self.lineProd1.setEnabled(False)
        self.lineProd1.setGeometry(QtCore.QRect(280, 330, 113, 20))
        self.lineProd1.setObjectName("lineProd1")
        self.lineInicio1 = QtWidgets.QLineEdit(self.tab)
        self.lineInicio1.setEnabled(False)
        self.lineInicio1.setGeometry(QtCore.QRect(90, 360, 113, 20))
        self.lineInicio1.setObjectName("lineInicio1")
        self.lineFin1 = QtWidgets.QLineEdit(self.tab)
        self.lineFin1.setEnabled(False)
        self.lineFin1.setGeometry(QtCore.QRect(280, 360, 113, 20))
        self.lineFin1.setObjectName("lineFin1")
        self.lineFin2 = QtWidgets.QLineEdit(self.tab)
        self.lineFin2.setEnabled(False)
        self.lineFin2.setGeometry(QtCore.QRect(710, 360, 113, 20))
        self.lineFin2.setObjectName("lineFin2")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(430, 330, 41, 16))
        self.label_9.setObjectName("label_9")
        self.lineProd2 = QtWidgets.QLineEdit(self.tab)
        self.lineProd2.setEnabled(False)
        self.lineProd2.setGeometry(QtCore.QRect(710, 330, 113, 20))
        self.lineProd2.setObjectName("lineProd2")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(630, 360, 41, 16))
        self.label_10.setObjectName("label_10")
        self.lineInicio2 = QtWidgets.QLineEdit(self.tab)
        self.lineInicio2.setEnabled(False)
        self.lineInicio2.setGeometry(QtCore.QRect(510, 360, 113, 20))
        self.lineInicio2.setObjectName("lineInicio2")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(630, 330, 61, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(430, 360, 41, 16))
        self.label_12.setObjectName("label_12")
        self.lineGen2 = QtWidgets.QLineEdit(self.tab)
        self.lineGen2.setEnabled(False)
        self.lineGen2.setGeometry(QtCore.QRect(510, 330, 113, 20))
        self.lineGen2.setObjectName("lineGen2")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(130, 400, 81, 16))
        self.label_13.setObjectName("label_13")
        self.linePos1 = QtWidgets.QLineEdit(self.tab)
        self.linePos1.setEnabled(True)
        self.linePos1.setGeometry(QtCore.QRect(210, 400, 113, 20))
        self.linePos1.setObjectName("linePos1")
        self.linePos2 = QtWidgets.QLineEdit(self.tab)
        self.linePos2.setEnabled(False)
        self.linePos2.setGeometry(QtCore.QRect(630, 400, 113, 20))
        self.linePos2.setObjectName("linePos2")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(550, 400, 81, 16))
        self.label_14.setObjectName("label_14")
        self.labelSonda_7 = QtWidgets.QLabel(self.tab)
        self.labelSonda_7.setGeometry(QtCore.QRect(10, 70, 31, 16))
        self.labelSonda_7.setObjectName("labelSonda_7")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(210, 640, 61, 16))
        self.label_15.setObjectName("label_15")
        self.lineProd3 = QtWidgets.QLineEdit(self.tab)
        self.lineProd3.setEnabled(False)
        self.lineProd3.setGeometry(QtCore.QRect(280, 640, 113, 20))
        self.lineProd3.setObjectName("lineProd3")
        self.linePos3 = QtWidgets.QLineEdit(self.tab)
        self.linePos3.setEnabled(False)
        self.linePos3.setGeometry(QtCore.QRect(210, 710, 113, 20))
        self.linePos3.setObjectName("linePos3")
        self.lineRV3 = QtWidgets.QLineEdit(self.tab)
        self.lineRV3.setEnabled(False)
        self.lineRV3.setGeometry(QtCore.QRect(140, 584, 261, 20))
        self.lineRV3.setObjectName("lineRV3")
        self.labelSonda_8 = QtWidgets.QLabel(self.tab)
        self.labelSonda_8.setGeometry(QtCore.QRect(10, 610, 90, 16))
        self.labelSonda_8.setObjectName("labelSonda_8")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(130, 710, 81, 16))
        self.label_16.setObjectName("label_16")
        self.labelReverse_3 = QtWidgets.QLabel(self.tab)
        self.labelReverse_3.setGeometry(QtCore.QRect(10, 584, 112, 16))
        self.labelReverse_3.setObjectName("labelReverse_3")
        self.lineFin3 = QtWidgets.QLineEdit(self.tab)
        self.lineFin3.setEnabled(False)
        self.lineFin3.setGeometry(QtCore.QRect(280, 670, 113, 20))
        self.lineFin3.setObjectName("lineFin3")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(220, 670, 41, 16))
        self.label_17.setObjectName("label_17")
        self.lineInicio3 = QtWidgets.QLineEdit(self.tab)
        self.lineInicio3.setEnabled(False)
        self.lineInicio3.setGeometry(QtCore.QRect(90, 670, 113, 20))
        self.lineInicio3.setObjectName("lineInicio3")
        self.labelForward_5 = QtWidgets.QLabel(self.tab)
        self.labelForward_5.setGeometry(QtCore.QRect(10, 460, 71, 16))
        self.labelForward_5.setObjectName("labelForward_5")
        self.labelForward_6 = QtWidgets.QLabel(self.tab)
        self.labelForward_6.setGeometry(QtCore.QRect(10, 558, 112, 16))
        self.labelForward_6.setObjectName("labelForward_6")
        self.lineFW3 = QtWidgets.QLineEdit(self.tab)
        self.lineFW3.setEnabled(False)
        self.lineFW3.setGeometry(QtCore.QRect(140, 558, 261, 20))
        self.lineFW3.setObjectName("lineFW3")
        self.geneCombo_3 = QtWidgets.QComboBox(self.tab)
        self.geneCombo_3.setEnabled(False)
        self.geneCombo_3.setGeometry(QtCore.QRect(9, 490, 75, 20))
        self.geneCombo_3.setObjectName("geneCombo_3")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.geneCombo_3.addItem("")
        self.lineSD3 = QtWidgets.QLineEdit(self.tab)
        self.lineSD3.setEnabled(False)
        self.lineSD3.setGeometry(QtCore.QRect(140, 610, 261, 20))
        self.lineSD3.setObjectName("lineSD3")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(10, 640, 41, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(10, 670, 41, 16))
        self.label_19.setObjectName("label_19")
        self.lineGen3 = QtWidgets.QLineEdit(self.tab)
        self.lineGen3.setEnabled(False)
        self.lineGen3.setGeometry(QtCore.QRect(90, 640, 113, 20))
        self.lineGen3.setObjectName("lineGen3")
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(0, 440, 821, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.geneCombo_4 = QtWidgets.QComboBox(self.tab)
        self.geneCombo_4.setEnabled(False)
        self.geneCombo_4.setGeometry(QtCore.QRect(429, 490, 75, 20))
        self.geneCombo_4.setObjectName("geneCombo_4")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.geneCombo_4.addItem("")
        self.lineGen4 = QtWidgets.QLineEdit(self.tab)
        self.lineGen4.setEnabled(False)
        self.lineGen4.setGeometry(QtCore.QRect(510, 640, 113, 20))
        self.lineGen4.setObjectName("lineGen4")
        self.lineSD4 = QtWidgets.QLineEdit(self.tab)
        self.lineSD4.setEnabled(False)
        self.lineSD4.setGeometry(QtCore.QRect(560, 610, 261, 20))
        self.lineSD4.setObjectName("lineSD4")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(550, 710, 81, 16))
        self.label_20.setObjectName("label_20")
        self.lineRV4 = QtWidgets.QLineEdit(self.tab)
        self.lineRV4.setEnabled(False)
        self.lineRV4.setGeometry(QtCore.QRect(560, 584, 261, 20))
        self.lineRV4.setObjectName("lineRV4")
        self.lineProd4 = QtWidgets.QLineEdit(self.tab)
        self.lineProd4.setEnabled(False)
        self.lineProd4.setGeometry(QtCore.QRect(700, 640, 113, 20))
        self.lineProd4.setObjectName("lineProd4")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(430, 670, 41, 16))
        self.label_21.setObjectName("label_21")
        self.lineInicio4 = QtWidgets.QLineEdit(self.tab)
        self.lineInicio4.setEnabled(False)
        self.lineInicio4.setGeometry(QtCore.QRect(510, 670, 113, 20))
        self.lineInicio4.setObjectName("lineInicio4")
        self.lineFin4 = QtWidgets.QLineEdit(self.tab)
        self.lineFin4.setEnabled(False)
        self.lineFin4.setGeometry(QtCore.QRect(700, 670, 113, 20))
        self.lineFin4.setObjectName("lineFin4")
        self.labelReverse_4 = QtWidgets.QLabel(self.tab)
        self.labelReverse_4.setGeometry(QtCore.QRect(430, 584, 112, 16))
        self.labelReverse_4.setObjectName("labelReverse_4")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(630, 640, 61, 16))
        self.label_22.setObjectName("label_22")
        self.linePos4 = QtWidgets.QLineEdit(self.tab)
        self.linePos4.setEnabled(False)
        self.linePos4.setGeometry(QtCore.QRect(630, 710, 113, 20))
        self.linePos4.setObjectName("linePos4")
        self.labelSonda_9 = QtWidgets.QLabel(self.tab)
        self.labelSonda_9.setGeometry(QtCore.QRect(430, 610, 90, 16))
        self.labelSonda_9.setObjectName("labelSonda_9")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(640, 670, 41, 16))
        self.label_23.setObjectName("label_23")
        self.labelForward_7 = QtWidgets.QLabel(self.tab)
        self.labelForward_7.setGeometry(QtCore.QRect(430, 558, 112, 16))
        self.labelForward_7.setObjectName("labelForward_7")
        self.lineFW4 = QtWidgets.QLineEdit(self.tab)
        self.lineFW4.setEnabled(False)
        self.lineFW4.setGeometry(QtCore.QRect(560, 558, 261, 20))
        self.lineFW4.setObjectName("lineFW4")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(430, 640, 41, 16))
        self.label_24.setObjectName("label_24")
        self.labelForward_8 = QtWidgets.QLabel(self.tab)
        self.labelForward_8.setGeometry(QtCore.QRect(430, 460, 71, 16))
        self.labelForward_8.setObjectName("labelForward_8")
        self.comboDianas = QtWidgets.QComboBox(self.tab)
        self.comboDianas.setGeometry(QtCore.QRect(560, 90, 75, 22))
        self.comboDianas.setObjectName("comboDianas")
        self.comboDianas.addItem("")
        self.comboDianas.addItem("")
        self.comboDianas.addItem("")
        self.comboDianas.addItem("")
        self.labelSonda_10 = QtWidgets.QLabel(self.tab)
        self.labelSonda_10.setGeometry(QtCore.QRect(450, 90, 101, 16))
        self.labelSonda_10.setObjectName("labelSonda_10")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QtCore.QRect(750, 870, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineTask = QtWidgets.QLineEdit(self.tab_3)
        self.lineTask.setEnabled(False)
        self.lineTask.setGeometry(QtCore.QRect(80, 50, 113, 20))
        self.lineTask.setObjectName("lineTask")
        self.labelTask = QtWidgets.QLabel(self.tab_3)
        self.labelTask.setGeometry(QtCore.QRect(20, 50, 47, 16))
        self.labelTask.setObjectName("labelTask")
        self.labelTask_2 = QtWidgets.QLabel(self.tab_3)
        self.labelTask_2.setGeometry(QtCore.QRect(20, 80, 47, 16))
        self.labelTask_2.setObjectName("labelTask_2")
        self.lineDb = QtWidgets.QLineEdit(self.tab_3)
        self.lineDb.setEnabled(False)
        self.lineDb.setGeometry(QtCore.QRect(80, 80, 113, 20))
        self.lineDb.setObjectName("lineDb")
        self.lineNombreOut = QtWidgets.QLineEdit(self.tab_3)
        self.lineNombreOut.setEnabled(True)
        self.lineNombreOut.setGeometry(QtCore.QRect(130, 530, 691, 20))
        self.lineNombreOut.setText("")
        self.lineNombreOut.setObjectName("lineNombreOut")
        self.labelTask_3 = QtWidgets.QLabel(self.tab_3)
        self.labelTask_3.setGeometry(QtCore.QRect(20, 530, 111, 16))
        self.labelTask_3.setObjectName("labelTask_3")
        self.labelMaxSeqs = QtWidgets.QLabel(self.tab_3)
        self.labelMaxSeqs.setGeometry(QtCore.QRect(250, 50, 91, 16))
        self.labelMaxSeqs.setObjectName("labelMaxSeqs")
        self.lineMaxSeqs = QtWidgets.QLineEdit(self.tab_3)
        self.lineMaxSeqs.setEnabled(True)
        self.lineMaxSeqs.setGeometry(QtCore.QRect(350, 50, 113, 20))
        self.lineMaxSeqs.setObjectName("lineMaxSeqs")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(20, 150, 141, 31))
        self.label_25.setObjectName("label_25")
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(20, 180, 231, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.checkBoxRemote = QtWidgets.QCheckBox(self.tab_3)
        self.checkBoxRemote.setEnabled(True)
        self.checkBoxRemote.setGeometry(QtCore.QRect(360, 180, 161, 18))
        self.checkBoxRemote.setObjectName("checkBoxRemote")
        self.lineMaxSeqs_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineMaxSeqs_2.setEnabled(True)
        self.lineMaxSeqs_2.setGeometry(QtCore.QRect(350, 80, 113, 20))
        self.lineMaxSeqs_2.setObjectName("lineMaxSeqs_2")
        self.labelMaxSeqs_2 = QtWidgets.QLabel(self.tab_3)
        self.labelMaxSeqs_2.setGeometry(QtCore.QRect(250, 80, 91, 16))
        self.labelMaxSeqs_2.setWhatsThis("")
        self.labelMaxSeqs_2.setObjectName("labelMaxSeqs_2")
        self.lineEditBlRV = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditBlRV.setGeometry(QtCore.QRect(170, 270, 281, 20))
        self.lineEditBlRV.setObjectName("lineEditBlRV")
        self.lineEditBlFW = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditBlFW.setGeometry(QtCore.QRect(170, 244, 281, 20))
        self.lineEditBlFW.setObjectName("lineEditBlFW")
        self.labelForward_9 = QtWidgets.QLabel(self.tab_3)
        self.labelForward_9.setGeometry(QtCore.QRect(20, 244, 131, 16))
        self.labelForward_9.setObjectName("labelForward_9")
        self.lineEditBlSD = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditBlSD.setGeometry(QtCore.QRect(170, 296, 281, 20))
        self.lineEditBlSD.setObjectName("lineEditBlSD")
        self.labelSonda_11 = QtWidgets.QLabel(self.tab_3)
        self.labelSonda_11.setGeometry(QtCore.QRect(20, 296, 111, 16))
        self.labelSonda_11.setObjectName("labelSonda_11")
        self.labelReverse_5 = QtWidgets.QLabel(self.tab_3)
        self.labelReverse_5.setGeometry(QtCore.QRect(20, 270, 131, 16))
        self.labelReverse_5.setObjectName("labelReverse_5")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelSonda_5 = QtWidgets.QLabel(self.tab_2)
        self.labelSonda_5.setObjectName("labelSonda_5")
        self.gridLayout_2.addWidget(self.labelSonda_5, 0, 0, 1, 1)
        self.lineFile_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineFile_2.setObjectName("lineFile_2")
        self.gridLayout_2.addWidget(self.lineFile_2, 1, 0, 1, 2)
        self.pushButtonFile_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonFile_2.setObjectName("pushButtonFile_2")
        self.gridLayout_2.addWidget(self.pushButtonFile_2, 2, 1, 1, 1)
        self.pushButtonFile_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButtonFile_3.setObjectName("pushButtonFile_3")
        self.gridLayout_2.addWidget(self.pushButtonFile_3, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineMScore, self.lineMMScore)
        MainWindow.setTabOrder(self.lineMMScore, self.lineOGScore)
        MainWindow.setTabOrder(self.lineOGScore, self.lineEGScore)
        MainWindow.setTabOrder(self.lineEGScore, self.pushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tab.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelSonda_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                           "font-size:10pt;\">Introduce "
                                                           "puntuaciones:</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Resumen"))
        self.pushButton.setText(_translate("MainWindow", "Alinear"))
        self.labelReverse.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                           "font-weight:600;\">RV Primer</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Extend Gap Score:"))
        self.labelSonda.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                         "font-weight:600;\">Sonda</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Mismatch Score:"))
        self.label.setText(_translate("MainWindow", "Match Score:"))
        self.label_3.setText(_translate("MainWindow", "Open Gap Score:"))
        self.labelForward.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                           "font-weight:600;\">FW Primer</span></p></body></html>"))
        self.labelSonda_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                           "font-size:10pt;\">Introduce los primers y la "
                                                           "sonda:</span></p></body></html>"))
        self.labelSonda_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                           "font-size:10pt;\">Seleccionar "
                                                           "archivo:</span></p></body></html>"))
        self.pushButtonFile.setText(_translate("MainWindow", "Abrir archivo"))
        self.geneCombo.setItemText(0, _translate("MainWindow", "-"))
        self.geneCombo.setItemText(1, _translate("MainWindow", ""))
        self.geneCombo.setItemText(2, _translate("MainWindow", ""))
        self.geneCombo.setItemText(3, _translate("MainWindow", ""))
        self.geneCombo.setItemText(4, _translate("MainWindow", ""))
        self.geneCombo.setItemText(5, _translate("MainWindow", ""))
        self.geneCombo.setItemText(6, _translate("MainWindow", ""))
        self.geneCombo.setItemText(7, _translate("MainWindow", ""))
        self.geneCombo.setItemText(8, _translate("MainWindow", ""))
        self.geneCombo.setItemText(9, _translate("MainWindow", ""))
        self.geneCombo.setItemText(10, _translate("MainWindow", ""))
        self.geneCombo.setItemText(11, _translate("MainWindow", ""))
        self.geneCombo.setItemText(12, _translate("MainWindow", ""))
        self.geneCombo.setItemText(13, _translate("MainWindow", ""))
        self.geneCombo.setItemText(14, _translate("MainWindow", ""))
        self.geneCombo.setItemText(15, _translate("MainWindow", ""))
        self.geneCombo.setItemText(16, _translate("MainWindow", ""))
        self.geneCombo.setItemText(17, _translate("MainWindow", ""))
        self.geneCombo.setItemText(18, _translate("MainWindow", ""))
        self.geneCombo.setItemText(19, _translate("MainWindow", ""))
        self.geneCombo.setItemText(20, _translate("MainWindow", ""))
        self.geneCombo.setItemText(21, _translate("MainWindow", ""))
        self.geneCombo.setItemText(22, _translate("MainWindow", ""))
        self.geneCombo.setItemText(23, _translate("MainWindow", ""))
        self.geneCombo.setItemText(24, _translate("MainWindow", ""))
        self.geneCombo.setItemText(25, _translate("MainWindow", ""))
        self.geneCombo.setItemText(26, _translate("MainWindow", ""))
        self.geneCombo.setItemText(27, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(0, _translate("MainWindow", "-"))
        self.geneCombo_2.setItemText(1, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(2, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(3, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(4, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(5, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(6, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(7, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(8, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(9, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(10, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(11, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(12, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(13, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(14, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(15, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(16, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(17, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(18, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(19, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(20, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(21, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(22, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(23, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(24, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(25, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(26, _translate("MainWindow", ""))
        self.geneCombo_2.setItemText(27, _translate("MainWindow", "E2"))
        self.labelForward_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; "
                                                             "font-weight:600;\">DIANA 1</span></p></body></html>"))
        self.labelForward_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; "
                                                             "font-weight:600;\">DIANA 2</span></p></body></html>"))
        self.labelSonda_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; "
                                                           "font-weight:600;\">Sonda</span></p></body></html>"))
        self.labelForward_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; "
                                                             "font-weight:600;\">FW Primer</span></p></body></html>"))
        self.labelReverse_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; "
                                                             "font-weight:600;\">RV Primer</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Gen"))
        self.label_6.setText(_translate("MainWindow", "Producto"))
        self.label_7.setText(_translate("MainWindow", "Inicio"))
        self.label_8.setText(_translate("MainWindow", "Fin"))
        self.label_9.setText(_translate("MainWindow", "Gen"))
        self.label_10.setText(_translate("MainWindow", "Fin"))
        self.label_11.setText(_translate("MainWindow", "Producto"))
        self.label_12.setText(_translate("MainWindow", "Inicio"))
        self.label_13.setText(_translate("MainWindow", "Posición +/-"))
        self.label_14.setText(_translate("MainWindow", "Posición +/-"))
        self.label_15.setText(_translate("MainWindow", "Producto"))
        self.labelSonda_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                           "font-weight:600;\">Sonda</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "Posición +/-"))
        self.labelReverse_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                             "font-weight:600;\">RV Primer</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "Fin"))
        self.labelForward_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; "
                                                             "font-weight:600;\">DIANA 3</span></p></body></html>"))
        self.labelForward_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                             "font-weight:600;\">FW Primer</span></p></body></html>"))
        self.geneCombo_3.setItemText(0, _translate("MainWindow", "-"))
        self.geneCombo_3.setItemText(1, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(2, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(3, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(4, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(5, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(6, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(7, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(8, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(9, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(10, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(11, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(12, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(13, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(14, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(15, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(16, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(17, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(18, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(19, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(20, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(21, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(22, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(23, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(24, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(25, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(26, _translate("MainWindow", ""))
        self.geneCombo_3.setItemText(27, _translate("MainWindow", "E3"))
        self.label_18.setText(_translate("MainWindow", "Gen"))
        self.label_19.setText(_translate("MainWindow", "Inicio"))
        self.geneCombo_4.setItemText(0, _translate("MainWindow", "-"))
        self.geneCombo_4.setItemText(1, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(2, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(3, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(4, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(5, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(6, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(7, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(8, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(9, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(10, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(11, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(12, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(13, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(14, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(15, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(16, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(17, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(18, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(19, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(20, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(21, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(22, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(23, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(24, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(25, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(26, _translate("MainWindow", ""))
        self.geneCombo_4.setItemText(27, _translate("MainWindow", "E4"))
        self.label_20.setText(_translate("MainWindow", "Posición +/-"))
        self.label_21.setText(_translate("MainWindow", "Inicio"))
        self.labelReverse_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                             "font-weight:600;\">RV Primer</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "Producto"))
        self.labelSonda_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                           "font-weight:600;\">Sonda</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "Fin"))
        self.labelForward_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                             "font-weight:600;\">FW Primer</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "Gen"))
        self.labelForward_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; "
                                                             "font-weight:600;\">DIANA 4</span></p></body></html>"))
        self.comboDianas.setItemText(0, _translate("MainWindow", "1"))
        self.comboDianas.setItemText(1, _translate("MainWindow", "2"))
        self.comboDianas.setItemText(2, _translate("MainWindow", "3"))
        self.comboDianas.setItemText(3, _translate("MainWindow", "4"))
        self.labelSonda_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                            "font-size:9pt;\">Número de "
                                                            "dianas:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Alignments"))
        self.pushButton_3.setText(_translate("MainWindow", "Blast"))
        self.lineTask.setText(_translate("MainWindow", "blastn-short"))
        self.labelTask.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                        "font-weight:600;\">Task</span></p></body></html>"))
        self.labelTask_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                          "font-weight:600;\">DB</span></p></body></html>"))
        self.lineDb.setText(_translate("MainWindow", "nt"))
        self.labelTask_3.setText(_translate("MainWindow", "<html><head/><body><p>Nombre archivo:</p></body></html>"))
        self.labelMaxSeqs.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                           "font-weight:600;\">Nº Max. Seq:</span></p></body></html>"))
        self.lineMaxSeqs.setText(_translate("MainWindow", "1000"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                       "font-weight:600;\">Formato de "
                                                       "Salida:</span></p></body></html>"))
        self.comboBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>rthftgh</p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Pairwise"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Query-anchored showing identities"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Query-anchored no identities"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Flat query-anchored, show identities"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Flat query-anchored, no identities"))
        self.comboBox.setItemText(5, _translate("MainWindow", "XML Blast output"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Tabular"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Tabular with comment lines"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Text ASN.1"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Binary ASN.1"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Comma-separated values"))
        self.comboBox.setItemText(11, _translate("MainWindow", "BLAST archive format (ASN.1)"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Seqalign (JSON)"))
        self.comboBox.setItemText(13, _translate("MainWindow", "Multiple-file BLAST JSON"))
        self.comboBox.setItemText(14, _translate("MainWindow", "Multiple-file BLAST XML2"))
        self.comboBox.setItemText(15, _translate("MainWindow", "Single-file BLAST JSON"))
        self.comboBox.setItemText(16, _translate("MainWindow", "Single-file BLAST XML2"))
        self.comboBox.setItemText(17, _translate("MainWindow", "Sequence Alignment/Map (SAM)"))
        self.comboBox.setItemText(18, _translate("MainWindow", "Organism Report"))
        self.checkBoxRemote.setText(_translate("MainWindow", "Remote"))
        self.lineMaxSeqs_2.setText(_translate("MainWindow", "10"))
        self.labelMaxSeqs_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                             "font-weight:600;\">Exp. "
                                                             "Evalue</span></p></body></html>"))
        self.labelForward_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                             "font-weight:600;\">FW Primer ("
                                                             "5\'-&gt;3\')</span></p></body></html>"))
        self.labelSonda_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                            "font-weight:600;\">Sonda ("
                                                            "5\'-&gt;3\')</span></p></body></html>"))
        self.labelReverse_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                             "font-weight:600;\">RV Primer ("
                                                             "5\'-&gt;3\')</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Blast"))
        self.labelSonda_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" "
                                                           "font-size:10pt;\">Seleccionar "
                                                           "archivo:</span></p></body></html>"))
        self.pushButtonFile_2.setText(_translate("MainWindow", "Abrir archivo"))
        self.pushButtonFile_3.setText(_translate("MainWindow", "Read"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Parser"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
